import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, GitBranch, History, Info, LockKeyhole, Play, ShieldCheck, X } from 'lucide-react';

type Audit = {id:string;timestamp:string;component:string;detail:string;hash:string;input_ref?:string;output_ref?:string;status?:string;idempotency_key?:string;decision_id?:string;[key:string]:unknown};
type ProofCase = {id:string;message:string;created_at:string;status:string;audit?:Audit[];policy?:{id?:string;reason:string;action:string;outcome:string;policy_version:string;evidence_refs?:string[];canonical_state?:string};actions?:{id:string;tool_name:string;idempotency_key:string}[];workflow?:{id:string;executor:string;stage:string;status:string;n8n_execution_id:string|null};verification?:{verified:boolean;expected:string;observed:string;evidence_refs:string[]};outcome_history?:{status:string;timestamp:string;reason:string}[];escalation?:{reason:string}};
const readable=(v:string)=>v.replaceAll('_',' ');
const steps=[['COMPLAINT','Complaint',''],['INTAKE','AI understand',''],['EVIDENCE','Evidence','evidence'],['PAYMENT_TWIN','Payment Twin','truth'],['POLICY','Policy','policy'],['ORCHESTRATION','n8n',''],['ACTION','Action','action'],['VERIFICATION','Verify','verify'],['OUTCOME','Outcome','done']];

export default function ResolveProof({value}:{value:ProofCase|undefined}){
 const [focus,setFocus]=useState(''),[replay,setReplay]=useState(false),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[why,setWhy]=useState(false);
 const events=value?.audit||[];
 useEffect(()=>{setFocus('');setReplay(false);setPlaying(false);setWhy(false);setCursor(0);},[value?.id]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setCursor(c=>{if(c>=events.length-1){setPlaying(false);return c;}return c+1;}),1100);return()=>clearInterval(id);},[playing,events.length]);
 const chosen=events.filter(e=>e.component===focus).at(-1);
 const acted=!!value?.actions?.some(a=>a.tool_name==='retry_merchant_notification');
 const terminal=value&&['RESOLVED','ESCALATED'].includes(value.status);
 const historical=events.slice(0,cursor+1);
 const stateAt=historical.filter(e=>e.component==='PAYMENT_TWIN'||e.component==='VERIFICATION').at(-1);
 const workspace='https://varmaleena.app.n8n.cloud';
 return <section className="r-proof r-card"><header><div><GitBranch size={19}/><h2>Resolution Graph</h2><span className="r-microtag">LIVE CASE STATE</span></div><div><button disabled={!value?.policy} onClick={()=>setWhy(!why)}><Info size={14}/>{acted?'Why did Resolve act?':'Why didn’t Resolve act?'}</button><button disabled={!events.length} onClick={()=>{setCursor(0);setReplay(true);}}><History size={14}/>Case replay</button></div></header>
 <div className="r-graph">{steps.map(([component,label,stage],i)=>{const recorded=events.filter(e=>e.component===component).at(-1);const orchestration=component==='ORCHESTRATION';const completed=orchestration?!!value?.workflow?.n8n_execution_id||value?.workflow?.executor==='local'&&events.some(e=>e.component==='ACTION'):component==='OUTCOME'?!!terminal:!!recorded;const active=!!value?.workflow&&(!terminal)&&(stage==='verify'?value.workflow.stage.startsWith('verify'):!!stage&&value.workflow.stage===stage);const blocked=component==='ACTION'&&value?.policy?.outcome==='ESCALATE';
  return <button aria-label={`Inspect ${label}`} onClick={()=>setFocus(focus===component?'':component)} key={component} className={(completed?'complete ':'')+(active?'active ':'')+(blocked?'blocked ':'')+(focus===component?'focused':'')}><span>{blocked?<LockKeyhole size={14}/>:completed?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><strong>{orchestration&&value?.workflow?.executor==='local'?'Local runner':label}</strong><small>{blocked?'Blocked':active?'In progress':completed?recorded?.timestamp?new Date(recorded.timestamp).toLocaleTimeString():value?.workflow?.status:'Waiting'}</small></button>;
 })}</div>
 {focus&&<div className="r-node-inspector"><strong>{steps.find(s=>s[0]===focus)?.[1]} · {chosen?.status||(focus==='ORCHESTRATION'?value?.workflow?.status:'Not executed')}</strong><p>{chosen?.detail||(focus==='ORCHESTRATION'?`${value?.workflow?.executor||'No'} workflow ${value?.workflow?.id||'not started'}`:'No audit evidence for this step yet.')}</p>{chosen&&<dl><dt>Timestamp</dt><dd>{chosen.timestamp}</dd><dt>Input reference</dt><dd>{chosen.input_ref||value?.id}</dd><dt>Output reference</dt><dd>{chosen.output_ref||chosen.id}</dd><dt>Policy decision</dt><dd>{chosen.decision_id||value?.policy?.id||'Not evaluated'}</dd>{chosen.idempotency_key&&<><dt>Idempotency key</dt><dd>{chosen.idempotency_key}</dd></>}</dl>}</div>}
 <div className="r-outcome-track">{['RESOLVED','MONITORING','BLOCKED','ESCALATED'].map(status=>{const previous=value?.outcome_history?.find(h=>h.status===status);return <span key={status} className={(previous?'visited ':'')+(value?.status===status?'current ':'')+status.toLowerCase()} title={previous?.reason}>{previous&&<Check size={11}/>} {status}</span>;})}<small>Outcomes follow evidence, not model confidence.</small></div>
 {value?.workflow?.executor==='n8n'&&<div className="r-n8n-link"><GitBranch size={15}/><strong>n8n Cloud</strong>{value.workflow.n8n_execution_id?<a href={`${workspace}/home/executions`} target="_blank" rel="noreferrer">Execution {value.workflow.n8n_execution_id} · open n8n <ArrowRight size={13}/></a>:<span>Awaiting authenticated execution callback</span>}</div>}
 {why&&value?.policy&&<div className="r-why"><h3><ShieldCheck size={18}/>{acted?'Why did Resolve do that?':'Why didn’t Resolve act?'}</h3><dl><dt>Why</dt><dd>{value.policy.reason}</dd><dt>Evidence at decision</dt><dd>{value.policy.canonical_state||'See Payment Twin'}<div>{value.policy.evidence_refs?.map(id=><code key={id}>{id}</code>)}</div></dd><dt>Policy</dt><dd>{value.policy.policy_version} · {value.policy.outcome}<code>{value.policy.id}</code></dd><dt>Permitted action</dt><dd>{value.policy.action}</dd><dt>Logical action</dt><dd>{value.actions?.map(a=><code key={a.id}>{a.tool_name} · {a.idempotency_key}</code>)||'No action yet'}</dd><dt>Verification</dt><dd>{value.verification?`${value.verification.verified?'Verified':'Not established'}: expected ${value.verification.expected}; observed ${value.verification.observed}.`:'Awaiting independent evidence.'}</dd><dt>Result</dt><dd>{value.status}{value.escalation&&<p>{value.escalation.reason}</p>}</dd></dl><p className="r-refusal-note">{value.policy.outcome==='MONITOR'?'Finality is unknown → financial action blocked → monitoring scheduled → customer informed.':value.policy.outcome==='ESCALATE'?'Conflicting, missing, or policy-restricted evidence blocks autonomous action. Human handoff preserves the evidence bundle.':'Notification acceptance is not success. Only a verified acknowledgement can close this case.'}</p></div>}
 {replay&&value&&<div className="r-replay-backdrop"><section className="r-replay" role="dialog" aria-modal="true" aria-label="Case replay"><button className="r-close" aria-label="Close replay" onClick={()=>{setReplay(false);setPlaying(false);}}><X size={19}/></button><span className="r-eyebrow">HISTORICAL AUDIT · NO ACTIONS EXECUTED</span><h2>Replay the resolution.</h2><p>{value.message}</p><div className="r-replay-controls"><button disabled={cursor===0} onClick={()=>{setPlaying(false);setCursor(c=>c-1);}}><ArrowLeft size={15}/></button><button onClick={()=>{if(cursor>=events.length-1)setCursor(0);setPlaying(!playing);}}><Play size={14}/>{playing?'Pause':'Play'}</button><span>Step {cursor+1} / {events.length}</span><button disabled={cursor>=events.length-1} onClick={()=>{setPlaying(false);setCursor(c=>c+1);}}><ArrowRight size={15}/></button></div><input aria-label="Replay step" type="range" min="0" max={Math.max(0,events.length-1)} value={cursor} onChange={e=>{setPlaying(false);setCursor(Number(e.target.value));}}/><div className="r-replay-step"><small>T+{Math.max(0,(Date.parse(events[cursor]?.timestamp||value.created_at)-Date.parse(value.created_at))/1000).toFixed(1)}s · {events[cursor]?.timestamp}</small><h3>{readable(events[cursor]?.component||'')}</h3><p>{events[cursor]?.detail}</p><dl><dt>State known at this step</dt><dd>{String(stateAt?.observed||stateAt?.detail||'Not yet derived')}</dd><dt>Input</dt><dd>{events[cursor]?.input_ref||value.id}</dd><dt>Output</dt><dd>{events[cursor]?.output_ref||events[cursor]?.id}</dd><dt>Policy decision</dt><dd>{String(historical.filter(e=>e.component==='POLICY').at(-1)?.decision_id||'Not evaluated yet')}</dd><dt>Audit hash</dt><dd>{events[cursor]?.hash}</dd>{events[cursor]?.idempotency_key&&<><dt>Idempotency key</dt><dd>{events[cursor].idempotency_key}</dd></>}</dl></div><div className="r-replay-index">{events.map((e,i)=><button key={e.id} className={cursor===i?'selected':''} onClick={()=>{setCursor(i);setPlaying(false);}}><span>{String(i+1).padStart(2,'0')}</span>{readable(e.component)}</button>)}</div></section></div>}
 </section>;
}
