import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, Check, ChevronRight, Download, Fingerprint, GitBranch, Headphones, Layers3, Loader2, Mic, Send, ShieldCheck, Sparkles, Volume2, X } from 'lucide-react';
import './resolve.css';
import ResolveProof from './ResolveProof';

type Role = 'customer'|'merchant'|'operations';
type Payment = {id:string;label:string;state:string;amount_paise:number};
type Trace = {id:string;timestamp:string;component:string;detail:string;hash:string;idempotency_key?:string;[key:string]:unknown};
type Twin = {canonical_state:string;amount_paise:number;version:string;merchant_ack:boolean;settled:boolean;evidence_refs:string[];conflicts:string[];missing_evidence:string[];events:{event_id:string;type:string;source:string;timestamp:string;payload_hash:string}[]};
type Case = {id:string;payment_id?:string;message:string;status:string;response:string;intent:string;created_at:string;severity:string;payment_state?:string;twin?:Twin;policy?:{id?:string;reason:string;outcome:string;action:string;policy_version:string;evidence_refs?:string[];canonical_state?:string};workflow?:{id:string;executor:string;stage:string;status:string;n8n_execution_id:string|null;checks:number};audit?:Trace[];actions?:{id:string;tool_name:string;idempotency_key:string}[];verification?:{verified:boolean;expected:string;observed:string;evidence_refs:string[]};ai?:{provider:string;model:string;fallback:boolean};outcome_history?:{status:string;timestamp:string;reason:string}[];explanation?:{text:string;provider:string};escalation?:{reason:string};};
const roleNames:Record<Role,string>={customer:'Customer',merchant:'Merchant',operations:'AI Operations'};
const title = (s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/^./,v=>v.toUpperCase());
const currency=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v/100);
const terminal=(c:Case)=>['RESOLVED','ESCALATED','NEEDS_INPUT'].includes(c.status);

export default function Resolve(){
 const [role,setRole]=useState<Role>('operations'),[token,setToken]=useState(sessionStorage.getItem('resolve-token-operations')||'resolve-operations-demo');
 const [cases,setCases]=useState<Case[]>([]),[payments,setPayments]=useState<Payment[]>([]),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[payment,setPayment]=useState('pay_confirmation'),[language,setLanguage]=useState('en-IN');
 const [memory,setMemory]=useState<{provider:string;boundary:string;context?:string;fallback_reason?:string;results:{id:string;text:string}[];related_cases:{case_id:string;resolution_note:string}[]}|null>(null),[memoryBusy,setMemoryBusy]=useState(false);
 const [failureScenario,setFailureScenario]=useState('conflict');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[session,setSession]=useState<{role:Role;executor:string;ai_configured:boolean;ai_provider:string;demo:boolean}|null>(null),[listening,setListening]=useState(false);
 const recognition=useRef<any>(null),generation=useRef(0),request=useRef<{body:string;id:string}|null>(null);
 const active=cases.find(c=>c.id===selected)||cases[0];
 async function api(path:string,body?:unknown){const r=await fetch('/v2'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(typeof v.detail==='string'?v.detail:'Please check the request and try again.');return v;}
 useEffect(()=>{let live=true;const gen=++generation.current;setCases([]);setPayments([]);setSession(null);setError('');
  Promise.all([api('/session'),api('/payments'),api('/cases')]).then(([s,p,c])=>{if(live&&gen===generation.current){setSession(s);setPayments(p);setCases(c);}}).catch(e=>live&&setError(e.message));
  const interval=setInterval(()=>api('/cases').then(c=>{if(live&&gen===generation.current)setCases(c);}).catch(e=>live&&setError(e.message)),1500);
  return()=>{live=false;clearInterval(interval);recognition.current?.abort();};
 },[token]);
 const changeRole=(r:Role)=>{setRole(r);setSelected('');setToken(sessionStorage.getItem('resolve-token-'+r)||`resolve-${r}-demo`);};
 async function submit(text=message,reference=payment){if(busy||text.trim().length<3)return;setBusy(true);setError('');const gen=generation.current;
  const body={message:text,payment_id:reference||null,language};const serialized=JSON.stringify(body);if(request.current?.body!==serialized)request.current={body:serialized,id:crypto.randomUUID()};
  try{const c=await api('/cases',{...body,request_id:request.current.id});if(gen===generation.current){setCases(old=>[c,...old.filter(x=>x.id!==c.id)]);setSelected(c.id);setMessage('');request.current=null;}}
  catch(e){if(gen===generation.current)setError((e as Error).message);}finally{setBusy(false);}}
 const demo=async(id:string,text:string)=>{try{if(session?.role==='operations'){const p=await api('/simulator/payments',{scenario:id.slice(4)});setPayments(old=>[p,...old]);setPayment(p.id);await submit(text,p.id);}else{setPayment(id);await submit(text,id);}}catch(e){setError((e as Error).message);}};
 useEffect(()=>{setMemory(null);},[active?.id,token]);
 async function loadMemory(){if(!active)return;setMemoryBusy(true);const gen=generation.current;try{const v=await api(`/cases/${active.id}/context`);if(gen===generation.current)setMemory(v);}catch(e){setError((e as Error).message);}finally{setMemoryBusy(false);}}
 async function attachReference(){if(!active||!payment)return;setBusy(true);try{const c=await api(`/cases/${active.id}/reference`,{payment_id:payment});setCases(old=>old.map(x=>x.id===c.id?c:x));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function injectSettlement(){if(!active?.payment_id)return;setBusy(true);try{await api(`/simulator/payments/${active.payment_id}/events`,{type:'SETTLED',request_id:active.id+':settled'});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function replay(){if(!active)return;setBusy(true);setError('');try{const c=await api(`/cases/${active.id}/replay`,{});setCases(old=>old.map(x=>x.id===c.id?c:x));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(){if(!active)return;try{const data=await api(`/cases/${active.id}/audit`);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=active.id+'.json';a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}
 function voice(){if(listening){recognition.current?.stop();return;}const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setError('Dictation is unavailable in this browser. Type your complaint below.');return;}const r=new Speech();recognition.current=r;r.lang=language;r.onresult=(e:any)=>setMessage(e.results[0][0].transcript);r.onerror=()=>{setError('Dictation failed. You can still type your complaint.');setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setError('Microphone could not start. Please type your complaint.');}}
 function speak(){if(!active)return;if(!('speechSynthesis'in window)){setError('Speech playback is unavailable.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(active.response);u.lang=language;speechSynthesis.speak(u);}
 const viewRole=session?.role||role;
 return <div className="resolve-app">
  <aside className="r-rail"><a className="r-logo" href="/" aria-label="Paytm Resolve"><Layers3 size={25}/></a><div className="r-rail-line"/><button className="r-rail-active" title="Resolution workspace"><Activity size={21}/></button><a href="/?view=finance" title="Existing finance dashboard"><Layers3 size={21}/></a><button onClick={()=>setSettings(true)} title="Role credentials"><Fingerprint size={21}/></button><span className="r-rail-bottom"><ShieldCheck size={21}/></span></aside>
  <div className="r-shell"><header className="r-header"><a href="/" className="r-wordmark">paytm<span>resolve</span><small>PAYMENT OPERATIONS</small></a><div className="r-role-switch" aria-label="Role view">{(Object.keys(roleNames) as Role[]).map(r=><button disabled={busy} className={viewRole===r?'active':''} key={r} onClick={()=>changeRole(r)}>{roleNames[r]}</button>)}</div><button className="r-profile" onClick={()=>setSettings(true)}><span>PR</span><div>{roleNames[viewRole]}<small>{session?.demo?'Synthetic demo identity':'Authenticated workspace'}</small></div></button></header>
  <main className="r-main"><div className="r-heading"><div><div className="r-eyebrow"><span/> LIVE RESOLUTION WORKSPACE</div><h1>{viewRole==='operations'?'Every payment. A clear answer.':viewRole==='customer'?'Let’s get your payment sorted.':'Clarity for your business.'}</h1><p>{viewRole==='operations'?'From a customer’s concern to a verified outcome. Follow every step.':'Report an issue and follow the same verified case across your workspace.'}</p></div><div className="r-system"><span className="r-dot"/>{session?.executor==='n8n'?'n8n orchestration configured':'Local workflow runner'}<small>{session?.ai_configured?`${session.ai_provider==='vertex'?'Vertex AI':'Gemini'} configured · fallback ready`:'Deterministic intake · no key required'}</small></div></div>
  {error&&<div className="r-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
  <div className="r-stats"><div><span>Cases in workspace</span><strong>{cases.length.toString().padStart(2,'0')}</strong><small>One case, three perspectives</small></div><div><span>Verified resolutions</span><strong>{cases.filter(c=>c.status==='RESOLVED').length.toString().padStart(2,'0')}<Check size={21}/></strong><small>Evidence before success</small></div><div><span>In progress</span><strong>{cases.filter(c=>!terminal(c)).length.toString().padStart(2,'0')}</strong><small>Bounded checks, durable state</small></div><div><span>Human review</span><strong>{cases.filter(c=>c.status==='ESCALATED').length.toString().padStart(2,'0')}</strong><small>Uncertainty is made explicit</small></div></div>
  <section className="r-demo"><div><Sparkles size={18}/><strong>Try the three journeys</strong><span>Real synthetic events. Visible verification.</span></div><button disabled={busy||!session} onClick={()=>demo('pay_confirmation','My payment succeeded but the merchant has no confirmation.')}>01 <b>Missing confirmation</b><ArrowRight size={15}/></button><button disabled={busy||!session} onClick={()=>demo('pay_pending','My payment is pending. Has it completed?')}>02 <b>Pending payment</b><ArrowRight size={15}/></button><button disabled={busy||!session} onClick={()=>demo('pay_settlement','Why is this payment not in my settlement?')}>03 <b>Settlement investigation</b><ArrowRight size={15}/></button></section>
  {viewRole==='operations'&&<ResolveProof value={active}/>}
  <div className={'r-workspace '+(viewRole!=='operations'?'r-scoped':'')}><section className="r-queue r-card"><div className="r-card-title"><h2>Case queue</h2><span>{cases.length}</span></div><p className="r-muted">Your latest payment conversations</p><div className="r-case-list">{cases.length===0?<div className="r-empty-small"><Headphones size={28}/><p>No cases yet.<br/>Choose a journey to begin.</p></div>:cases.map(c=><button key={c.id} className={'r-case '+(active?.id===c.id?'selected':'')} onClick={()=>setSelected(c.id)}><div><span className={'r-status-dot '+c.status.toLowerCase()}/><small>{c.id.slice(-8).toUpperCase()}</small><ChevronRight size={14}/></div><strong>{c.message}</strong><footer><span className={'r-badge '+c.status.toLowerCase()}>{title(c.status)}</span><time>{new Date(c.created_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time></footer></button>)}</div><div className="r-safety-note"><ShieldCheck size={18}/><p>Financial truth comes from validated events. AI cannot move money.</p></div></section>
  <section className="r-center r-card"><div className="r-card-title"><h2>{viewRole==='operations'?'Resolution timeline':'Your resolution'}</h2>{active&&<span className={'r-badge '+active.status.toLowerCase()}>{title(active.status)}</span>}</div>
  {active?<><div className="r-complaint"><span className="r-avatar">{viewRole==='merchant'?'M':'C'}</span><div><small>REPORTED CONCERN · {active.payment_id||'REFERENCE NEEDED'}</small><p>{active.message}</p></div></div>
  {viewRole==='operations'?<div className="r-timeline">{active.audit?.map((a,i)=><div className="r-trace" key={a.id}><span className={'r-trace-icon '+(a.component==='ESCALATION'?'amber':'')}><Check size={13}/></span><div><header><strong>{title(a.component)}</strong><time>{new Date(a.timestamp).toLocaleTimeString()}</time></header><p>{a.detail}</p>{a.idempotency_key&&<code>{a.idempotency_key}</code>}{i===0&&active.ai&&<span className="r-microtag">{active.ai.provider} · {active.ai.model}</span>}</div></div>)}{!terminal(active)&&<div className="r-trace r-processing"><span className="r-trace-icon"><Loader2 size={14} className="r-spin"/></span><div><strong>{active.workflow?.stage?.startsWith('verify')?'Waiting for verification evidence':'Processing evidence'}</strong><p>The timeline updates as the workflow advances.</p></div></div>}</div>:<div className="r-customer-state"><ShieldCheck size={32}/><h3>{title(active.payment_state||active.twin?.canonical_state||active.status)}</h3><p>{active.verification?.verified?'The expected result is verified against payment evidence.':'We will only confirm the outcome when the evidence supports it.'}</p></div>}
  <div className={'r-outcome '+(active.status==='RESOLVED'?'success':'')}><div><Sparkles size={17}/><strong>{active.status==='RESOLVED'?'Verified outcome':active.status==='ESCALATED'?'Handed to human review':'Current update'}</strong><button onClick={speak} title="Read update aloud"><Volume2 size={16}/></button></div><p>{active.explanation?.text||active.response}</p>{active.explanation&&<small className="r-microtag">Gemini · verified facts only</small>}</div></>:<div className="r-welcome"><span><GitBranch size={40}/></span><h2>A resolution you can follow.</h2><p>Start with a complaint. Watch evidence become a payment state, a policy decision, and a verified outcome.</p><div><b>Evidence</b><ArrowRight size={13}/><b>Action</b><ArrowRight size={13}/><b>Verification</b></div></div>}
  {active?.status==='NEEDS_INPUT'&&<button className="r-primary" disabled={!payment||busy} onClick={attachReference}>Attach selected reference to this case</button>}
  <form className="r-composer" onSubmit={e=>{e.preventDefault();submit();}}><div><select aria-label="Payment reference" value={payment} onChange={e=>setPayment(e.target.value)}><option value="">No reference yet</option>{payments.map(p=><option key={p.id} value={p.id}>{p.id} · {currency(p.amount_paise)}</option>)}</select><select aria-label="Language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en-IN">English</option><option value="hi-IN">हिन्दी</option></select></div><textarea aria-label="Describe your payment issue" placeholder="Tell us what happened with your payment…" value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/><footer><button type="button" className={listening?'r-recording':''} onClick={voice}><Mic size={17}/>{listening?'Stop listening':'Voice input'}</button><button className="r-primary" disabled={busy||!session||message.trim().length<3}>{busy?<Loader2 size={16} className="r-spin"/>:<Send size={15}/>}Create case</button></footer></form></section>
  {viewRole!=='customer'&&<aside className="r-evidence"><section className="r-card"><div className="r-card-title"><h2><Layers3 size={16}/> Payment Twin</h2><span className="r-microtag">DETERMINISTIC</span></div>{active?.twin?<><div className="r-twin-state"><small>CANONICAL STATE</small><strong>{title(active.twin.canonical_state)}</strong><span>{currency(active.twin.amount_paise)} <i>INR</i></span></div><div className="r-state-row"><span>Merchant acknowledgement</span><b>{active.twin.merchant_ack?'Verified':'Missing'}</b></div><div className="r-state-row"><span>Settlement completion</span><b>{active.twin.settled?'Verified':'Not observed'}</b></div><div className="r-evidence-label">EVIDENCE LEDGER <span>{active.twin.events.length} events</span></div>{active.twin.events.map(e=><div className="r-event" key={e.event_id}><Check size={13}/><div><strong>{title(e.type)}</strong><small>{e.source}</small></div></div>)}{active.twin.conflicts.map(x=><p className="r-warning" key={x}>{x}</p>)}{active.twin.missing_evidence.length>0&&<p className="r-warning">Missing: {active.twin.missing_evidence.join(', ')}</p>}<code className="r-version">State version {active.twin.version}</code></>:<p className="r-placeholder">Payment state and its supporting events appear here when a case begins.</p>}</section>
  <section className="r-card r-policy"><div className="r-card-title"><h2><ShieldCheck size={16}/> Policy decision</h2></div>{active?.policy?<><span className={'r-policy-outcome '+active.policy.outcome.toLowerCase()}>{active.policy.outcome==='ALLOW'?'Safe action permitted':title(active.policy.outcome)}</span><p>{active.policy.reason}</p><code>{active.policy.action}</code><small>{active.policy.policy_version}</small></>:<p className="r-placeholder">Explicit rules decide which action is permitted.</p>}</section><section className="r-card r-memory"><div className="r-card-title"><h2><Layers3 size={16}/> Support memory</h2><span className="r-microtag">ADVISORY ONLY</span></div><p>Support playbooks and similar resolution notes. Never a source of payment truth.</p><button disabled={!active||memoryBusy} onClick={loadMemory}>{memoryBusy?<Loader2 size={13} className="r-spin"/>:<Sparkles size={13}/>}Retrieve context</button>{memory&&<div><small>{memory.provider==='cognee'?'Cognee knowledge graph':'Local support playbooks'}</small>{memory.fallback_reason&&<p>{memory.fallback_reason}</p>}{memory.context&&<p className="r-memory-context">{memory.context}</p>}{memory.results.map(item=><details key={item.id}><summary>{item.id.replaceAll('_',' ')}</summary><p>{item.text}</p></details>)}{memory.related_cases.map(item=><details key={item.case_id}><summary>Similar resolved case · {item.case_id.slice(-8)}</summary><p>{item.resolution_note}</p></details>)}</div>}</section></aside>}
  </div>
  {viewRole==='operations'&&<section className="r-workflow r-card"><div className="r-workflow-heading"><div><GitBranch size={19}/><h2>Workflow execution</h2><span className="r-microtag">{active?.workflow?.executor==='n8n'?'N8N':'LOCAL RUNNER'}</span></div><div><button disabled={!active?.actions?.length||busy} onClick={replay}><Fingerprint size={15}/>Replay action</button><button disabled={!active} onClick={download}><Download size={15}/>Audit packet</button></div></div><div className="r-nodes">{['Intake','Evidence','Payment Twin','Policy','Action','Verification','Outcome'].map((n,i)=>{const events=active?.audit||[];const done=i===0?!!active:i===6?!!active&&terminal(active):events.some(e=>e.component===n.toUpperCase().replaceAll(' ','_'));return <div className={done?'done':''} key={n}><span>{done?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><strong>{n}</strong>{i<6&&<ArrowRight size={16}/>}</div>;})}</div><footer><span>{active?.workflow?`Run ${active.workflow.id} · ${active.workflow.status}`:'A real execution trace will appear when you create a case.'}</span><span>{active?.workflow?.n8n_execution_id?`n8n execution ${active.workflow.n8n_execution_id}`:'No external execution claimed'}</span></footer></section>}
  {viewRole==='operations'&&<section className="r-simulator"><div><ShieldCheck size={16}/><strong>Safety lab</strong><span>Challenge the resolution engine with synthetic evidence.</span></div><select aria-label="Failure scenario" value={failureScenario} onChange={e=>setFailureScenario(e.target.value)}><option value="conflict">Conflicting capture and failure</option><option value="notification_failure">Acknowledgement never arrives</option><option value="settled">Verified settlement</option></select><button disabled={busy||!session} onClick={()=>demo('pay_'+failureScenario,failureScenario==='settled'?'Explain settlement':'Investigate this payment')}>Run scenario <ArrowRight size={13}/></button>{active?.intent==='SETTLEMENT'&&!terminal(active)&&<button disabled={busy} onClick={injectSettlement}>Simulate settlement arrival</button>}</section>}
  <footer className="r-footer"><span><ShieldCheck size={13}/>Synthetic payment data · No live Paytm connection · No money movement</span><a href="/?view=finance">Open finance dashboard <ArrowRight size={13}/></a></footer>
  </main></div>
  {settings&&<div className="r-modal-bg"><section className="r-modal" role="dialog" aria-modal="true" aria-label="Role credentials"><button className="r-close" onClick={()=>setSettings(false)} aria-label="Close settings"><X size={18}/></button><Fingerprint size={28}/><h2>Workspace access</h2><p>The API binds each credential to a role and owner. Selecting a view does not grant access to another role’s data.</p><label>Credential for {roleNames[role]}<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><p>Local demo credentials are intentionally public. For hosting, configure private identities on the server and disable demo access.</p><button className="r-primary" onClick={()=>{sessionStorage.setItem('resolve-token-'+role,token);setSettings(false);}}>Save credential</button></section></div>}
 </div>;
}
